### ISSUE TITLE
Wasn't able to get basic setup working

### ISSUE THREAD

**Issue by garrettlancaster** [jgaskins/clearwater#7]
Followed steps with Ruby 2.1.3, fresh Rails 4.2 app, and opal-haml.  The engine seems to be interpreting app/assets/javascripts/templates/application.haml as ruby.  Plain text in said file throws an undefined method error (trying to call the text as a method).  Using a tag of any kind threw an EOF while still in string error.

I like the project, hope you can get it off the ground.

**Comment by jgaskins** [comment]
I just tested it out and it looks like the `opal-haml` gem needs to use the GitHub version. Adding this in my Gemfile instead of the released version fixed it for me:

```ruby
gem 'opal-haml', github: 'opal/opal-haml'
```

It appears [this commit](https://github.com/opal/opal-haml/commit/1ebed53311a0a36ce4650a8838802d039a4dddd1) is what fixed it (I wonder if the Opal `Template` API changed. I remember having similar problems getting `opal-slim` working until I added similar code to it.

If you could check that the `opal-haml` GitHub ref works for you and let me know, I'll go ahead and update the Clearwater README to add that into the Gemfile.

**Comment by garrettlancaster** [comment]
Unfortunately still a no-go. Here’s a repo with the app in case I’m missing something https://github.com/garrettlancaster/clearwater

**Comment by jgaskins** [comment]
After cloning, bundling, and starting the Rails server, your app worked for me :-)

![Garrett's Clearwater app](https://cloud.githubusercontent.com/assets/108205/5812494/0a8f2c88-a03a-11e4-9565-5a4893f1117d.png)

**Comment by jgaskins** [comment]
Try `rm -rf tmp/cache` before running your Rails server. It may have cached some of the old compiled Opal code.

**Comment by garrettlancaster** [comment]
Yep, that was it!

**Comment by jgaskins** [comment]
Awesome! I've gone ahead and updated the README to reflect the GitHub dependency for `opal-haml`, so it should be a bit clearer for people who are building their apps with Haml.
